config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root to: 'tasks#index'
  
  resources :users, only: [:new, :create, :show, :edit, :update]

  namespace :admin do
    resources :users
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :tasks 
    # collection do
    #   get 'search'
    # end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :user, optional: true
  has_many :labellings, dependent: :destroy
  has_many :labels, through: :labellings

  validates :name, presence: true
  validates :description, presence: true
  validates :end_date, presence: true
  validates :status, presence: true
  validates :priority, presence: true
  validate :pretend_ago

  def pretend_ago
    errors.add(:end_date, ' 過去の日付は入力できません') if end_date.nil? || end_date < Date.today
  end

  scope :get_by_name, ->(name) {
    where("name like ?", "%#{name}%")
  }
  
  scope :get_by_status, ->(status) {
    where(status: status)
  }

  scope :search_with_label, -> (label) {
    return if label.blank?
    joins(:labels).where('labels.id = ?', label)
  }


  enum priority: %i[High Middle Low]


end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # helper_method :sort_column, :sort_direction
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, only:[:show, :edit, :update, :destroy]
  before_action :authenticate_user, only:[:index, :show, :edit, :update, :destroy]

  def index
    sort_column = params[:column]
    # binding.pry
    if params[:direction]
      @tasks = Task.all.order(sort_column + ' ' + sort_direction)
    else
      @tasks = Task.all.order(created_at: :desc)
    end

    if params[:name].present?
      @tasks = @tasks.get_by_name params[:name]
    end
    if params[:status].present?
      @tasks = @tasks.get_by_status params[:status]
    end
    if params[:label_name].present?
      @tasks = @tasks.search_with_label(params[:label_name])
    else
      @tasks = @tasks.all
    end
  
    @tasks = @tasks.page(params[:page]).per(7)
  
  end

  def show
  end

  def new
    @task = Task.new
  end

  def edit
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, notice: "タスク「#{@task.name}」を登録しました。"
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: "タスク「#{@task.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy
    redirect_to tasks_url, notice: "タスク「#{task.name}」を削除しました。"
  end


  private

  def task_params
    params.require(:task).permit(:name, :description, :end_date, :status, :priority, { label_ids: [] })
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
  end

  def ensure_correct_user
    @task = Task.find(params[:id])
    if current_user.id != @task.user.id
      flash[:notice] = "権限がありません"
      redirect_to root_path
    end
  end
  
end

app/helpers/tasks_helper.rb
module TasksHelper
  # def sort_asc(column_to_be_sorted)
  #   link_to "▲", {:column => column_to_be_sorted, :direction => "asc"}
  # end

  # def sort_desc(column_to_be_sorted)
  #   link_to "▼", {:column => column_to_be_sorted, :direction => "desc"}
  # end



end

app/views/tasks/_form.html.slim
/ | require "date"
= form_with model: task, local: true do |f|
  - if @task.errors.any?
    #error_explanation
      h2
        = @task.errors.count
        | 件のエラーがあります。
      ul
        - @task.errors.full_messages.each do |msg|
          li= msg
          
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
  .form-group
    = f.label :end_date
    = f.date_field :end_date
  .form-group
    = f.label :status
    = f.select :status, ["未着手","着手中","完了"]
  .form-group
    = f.label :priority
    = f.select :priority, Task.priorities.keys.map {|k| [t("enums.task.priority.#{k}"), k]}
  .form-group
    = f.label :label_name
    = f.collection_check_boxes(:label_ids, Label.all, :id, :label_name)

    / - Label.all.each do |label|
    /   = f.check_box :label_ids, { multiple: true, checked: label[:checked], disabled: label[:disabled], include_hidden: false }, label[:id] 
        label style=("background-color: yellow") = label_name
  br/
  = f.submit nil, class: 'btn btn-primary'

app/views/tasks/edit.html.slim
h1 タスクの編集

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }

app/views/tasks/index.html.slim
/ p= notice
h1 タスク一覧

= link_to '新規登録', new_task_path, class: 'btn btn-primary'

div
  = form_tag(tasks_path, method: "get") do
    = label_tag :name, "タイトル"
    = text_field_tag :name, params[:name]
    = label_tag :status, "状態"
    = select_tag :status, 
      options_for_select([["未着手", "未着手"],["着手中","着手中"],["完了","完了"]]),
      include_blank: true
    = label_tag :label_name, "ラベル"
    / - binding.pry
    = select_tag :label_name, options_for_select(Label.pluck(:label_name, :id)),
      include_blank: true
    / = select_tag :label_name, 
    /   options_for_select("label_id", Label.pluck(:label_name, :id)),

    / = label_tag :label_search, t('.label_search'), value: params[:label]

    / = select_tag :label_name, 
    /   options_for_select("label_id", Label.pluck(:label_name, :id)),
    /   include_blank: true
    
    / Label.pluck(:label_name, :id)
    / - binding.pry
    / include_blank: true
    / , Label.pluck(:label_name, :id), { include_blank: true }
    / options_for_select([["HTML", "HTML"],["CSS","CSS"],["Ruby","Ruby"],["Rails","Rails"],["PHP","PHP"],["Java","Java"]]),
    = submit_tag "検索"

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th= Task.human_attribute_name(:user_name)
      th= Task.human_attribute_name(:title)
      th= Task.human_attribute_name(:created_at)
      th
        = Task.human_attribute_name(:end_date)
        = sort_asc("end_date")
        = sort_desc("end_date")
      th= Task.human_attribute_name(:status)
      th
        = Task.human_attribute_name(:priority)
        = sort_asc("priority")
        = sort_desc("priority")
      th= Task.human_attribute_name(:label)

  tbody
    - @tasks.each do |task|
      tr.task_row
        td= task.user.user_name
        td= link_to task.name, task
        td= task.created_at.to_s(:timeform)
        td= task.end_date.to_s(:default)
        td= task.status
        td= t("enums.task.priority.#{task.priority}")
        td 
          - task.labels.each do |label|
            = label.label_name
        td
          = link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3'
          = link_to '削除', task, method: :delete, data: { confirm: "タスク「#{task.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

= link_to '管理画面入り口', admin_users_path,  data: { confirm: "管理者以外は権限がありません" }

div
  = paginate @tasks

app/views/tasks/new.html.slim
h1 タスクの新規登録

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: { task: @task }

app/views/tasks/show.html.slim
h1 タスクの詳細

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= Task.human_attribute_name(:id)
      td= @task.id
    tr
      th= Task.human_attribute_name(:name)
      td= @task.name
    tr
      th= Task.human_attribute_name(:description)
      td= simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div")
    tr
      th= Task.human_attribute_name(:created_at)
      td= @task.created_at
    tr
      th= Task.human_attribute_name(:end_date)
      td= @task.end_date
    tr
      th= Task.human_attribute_name(:status)
      td= @task.status
    tr
      th= Task.human_attribute_name(:priority)
      td= @task.priority
    tr
      th= Task.human_attribute_name(:label)
      td
        - @task.labels.each do |label|
          = label.label_name

    tr
      th= Task.human_attribute_name(:updated_at)
      td= @task.updated_at

= link_to '編集', edit_task_path, class: 'btn btn-primary mr-3'
= link_to '削除', @task, method: :delete, data: { confirm: "タスク「#{@task.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'