config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root to: 'tasks#index'
  
  resources :users, only: [:new, :create, :show, :edit, :update]

  namespace :admin do
    resources :users
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :tasks 
    # collection do
    #   get 'search'
    # end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end

app/models/label.rb
class Label < ApplicationRecord
  has_many :labellings, dependent: :destroy
  has_many :tasks, through: :labellings
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy]

  # GET /labels
  def index
    @labels = Label.all
  end

  # GET /labels/1
  def show
  end

  # GET /labels/new
  def new
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
  end

  # POST /labels
  def create
    @label = Label.new(label_params)

    if @label.save
      redirect_to @label, notice: 'Label was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /labels/1
  def update
    if @label.update(label_params)
      redirect_to @label, notice: 'Label was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /labels/1
  def destroy
    @label.destroy
    redirect_to labels_url, notice: 'Label was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_label
      @label = Label.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def label_params
      params.require(:label).permit(:label_name)
    end
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_form.html.slim
= form_for @label do |f|
  - if @label.errors.any?
    #error_explanation
      h2 = "#{pluralize(@label.errors.count, "error")} prohibited this label from being saved:"
      ul
        - @label.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :label_name
    = f.text_field :label_name
  .actions = f.submit

app/views/labels/edit.html.slim
h1 Editing label

== render 'form'

=> link_to 'Show', @label
'|
=< link_to 'Back', labels_path

app/views/labels/index.html.slim
h1 Listing labels

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @labels.each do |label|
      tr
        td = label.label_name
        td = link_to 'Show', label
        td = link_to 'Edit', edit_label_path(label)
        td = link_to 'Destroy', label, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Label', new_label_path

app/views/labels/new.html.slim
h1 New label

== render 'form'

= link_to 'Back', labels_path

app/views/labels/show.html.slim
p#notice = notice

p
  strong Name:
  = @label.label_name

=> link_to 'Edit', edit_label_path(@label)
'|
=< link_to 'Back', labels_path