config/routes.rb
Rails.application.routes.draw do
  resources :labels
  root to: 'tasks#index'
  
  resources :users, only: [:new, :create, :show, :edit, :update]

  namespace :admin do
    resources :users
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :tasks 
    # collection do
    #   get 'search'
    # end
end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# end

app/models/user.rb
class User < ApplicationRecord

  before_destroy :do_not_destroy_last_admin

  # validation
  validates :user_name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :email, uniqueness: true
  before_validation { email.downcase! }
  validates :password, presence: true, length: { minimum: 6 }, on: :new

  has_secure_password
  has_many :tasks, dependent: :destroy

  private

  def do_not_destroy_last_admin
    if self.admin? && User.where(admin: :true).count == 1
      throw :abort
    end
  end

  enum priority: %i[High Middle Low]
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:index, :create, :destroy, :edit, :update]


  # GET /users
  def index
    @users = User.all
    @tasks = Task.all.includes(:user)
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = Use.new(user_params)
      if user.save
        redirect_to admin_users_path, notice: "ユーザー「#{@user.user_name}」を登録しました"
      else
        render :new
      end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to admin_users_path(@user), notice: "ユーザー「#{@user.user_name}」を更新しました"
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: "ユーザー「#{@user.user_name}」を削除しました"
    else
      redirect_to admin_users_path, notice: "管理者「#{@user.user_name}」は削除できません"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_params
      params.require(:user).permit(:user_name, :email, :admin, :password,
                                  :password_confirmation)
    end

    def admin_user
      if current_user.admin?
      else
        redirect_to root_path 
        flash[:notice] = "あなたは管理者ではありません"
      end
    end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # helper_method :sort_column, :sort_direction
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, only:[:show, :edit, :update, :destroy]
  before_action :authenticate_user, only:[:show, :edit, :update, :destroy]
  
  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
    sort_column = params[:column]
    if params[:direction]
      # binding.pry
      @tasks = @user.tasks.all.order(sort_column + ' ' + sort_direction)
    else
      @tasks = @user.tasks.all.order(created_at: :desc)
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id), notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /users/1
  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_name, :email, :password,
                                :password_confirmation)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    if current_user.admin?
    elsif current_user.id != @user.id
      flash[:notice] = "権限がありません"
      redirect_to tasks_path
    end
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end

end

app/helpers/users_helper.rb
module UsersHelper
  # def sort_asc(column_to_be_sorted)
  #   link_to "▲", {:column => column_to_be_sorted, :direction => "asc"}
  # end

  # def sort_desc(column_to_be_sorted)
  #   link_to "▼", {:column => column_to_be_sorted, :direction => "desc"}
  # end
end

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :user_name
    = f.label :email
    = f.email_field :email
    = f.label :password
    = f.password_field :password
    = f.label :password_confirmation
    = f.password_field :password_confirmation
    br/
    = f.submit "Update my account"

= link_to 'ユーザーページに戻る', user_path(current_user.id)

app/views/users/_user.html.slim
li
  = gravatar_for user, size: 50
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    | | #{link_to "delete", user, method: :delete,
data: { confirm: "You sure?" }}

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 ユーザー管理画面

table
  thead
    tr
      th ユーザーID
      th Name
      th
      th

  tbody
    - @users.each do |user|
      tr
        td = user.id
        td = user.user_name
        td = link_to 'Show', user
        td = link_to 'Edit', edit_user_path(user)
        td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New User', new_user_path

app/views/users/new.html.slim
h1 Sign up

- if @user.errors.any?
  #error_explanation
    h2
      = pluralize(@user.errors.count, "error")
      | prohibited this #{@user.user_name} from being saved:
    ul
      - @user.errors.full_messages.each do |message|
        li= message

= form_with(model: @user, local: true) do |f|
  = f.label :name
  = f.text_field :user_name
  = f.label :email
  = f.email_field :email
  = f.label :password
  = f.password_field :password
  = f.label :password_confirmation
  = f.password_field :password_confirmation
  = f.submit "Create account"

app/views/users/show.html.slim
/ p#notice = notice

h1
  = @user.user_name
  | のページ
p
  | メールアドレス: #{@user.email}

=> link_to 'Edit', edit_user_path(@user)

br/
br/
= link_to '新規登録', new_task_path, class: 'btn btn-primary'

.mb-3
h2.heading List of my tasks
table.table.table-hover
  thead.thead-default
    tr
      th= Task.human_attribute_name(:name)
      th= Task.human_attribute_name(:created_at)
      th
        = Task.human_attribute_name(:end_date)
        = sort_asc("end_date")
        = sort_desc("end_date")
      th= Task.human_attribute_name(:status)
      th
        = Task.human_attribute_name(:priority)
        = sort_asc("priority")
        = sort_desc("priority")
      th= Task.human_attribute_name(:label)

  tbody
    - @tasks.each do |task|
      tr.task_row
        td= link_to task.name, task
        td= task.created_at.to_s(:timeform)
        td= task.end_date.to_s(:default)
        td= task.status
        td= t("enums.task.priority.#{task.priority}")
        td 
          - task.labels.each do |label|
            = label.label_name
        td
          = link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3'
          = link_to '削除', task, method: :delete, data: { confirm: "タスク「#{task.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'

= link_to 'タスク一覧ページ', tasks_path